export type QualityState = "raw" | "polished" | "publishable" | "indexable-ready";

export type PublicationEntry = {
  slug: string;
  published: boolean;
  indexable: boolean;
  qualityState: QualityState;
  reviewer: string;
  reviewedAt: string;
  notes?: string;
};

export const publicationManifest: PublicationEntry[] = [
  {
    slug: "cpvc-fundamentals-hub",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "technical-guides-hub",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "installation-and-joining-hub",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "problems-and-fixes-hub",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "standards-and-sizing-hub",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "what-is-cpvc-pipe",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "cpvc-temperature-limit",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "can-cpvc-handle-hot-water",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "where-cpvc-should-not-be-used",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
    notes: "Ready to publish; keep indexability under review if the exclusion cluster grows too quickly.",
  },
  {
    slug: "how-to-join-cpvc-pipes",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "cpvc-support-spacing",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
    notes: "Strong supporting page; monitor whether a fuller spacing table is needed before long-term indexing.",
  },
  {
    slug: "why-cpvc-pipes-crack",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "why-cpvc-joints-leak",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "is-15778-explained",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Compliance Review",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "how-to-size-cpvc-for-a-house",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
    notes: "Ready for publication; can become indexable-ready after deeper sizing examples are added.",
  },
  {
    slug: "cpvc-vs-upvc",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "cpvc-vs-ppr",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
    notes: "Publishable and useful; indexability can scale after more installation-specific evidence is added.",
  },
  {
    slug: "cpvc-vs-copper",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "cpvc-vs-gi-pipe",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "cpvc-vs-pvc",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "can-cpvc-handle-boiling-water",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "how-long-does-cpvc-last",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "does-sunlight-damage-cpvc",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "is-cpvc-safe-for-drinking-water",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Compliance Review",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "can-cpvc-be-threaded",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "solvent-cement",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "cts",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "sdr",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "water-hammer",
    published: true,
    indexable: true,
    qualityState: "publishable",
    reviewer: "Editorial Desk",
    reviewedAt: "2026-04-07",
  },
  {
    slug: "pressure-derating",
    published: true,
    indexable: true,
    qualityState: "indexable-ready",
    reviewer: "Technical Review Team",
    reviewedAt: "2026-04-07",
  },
];

export const publicationManifestBySlug = new Map(publicationManifest.map((entry) => [entry.slug, entry]));
